// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/era.proto

package era

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CurrentEraMessage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CurrentEraMessage) Reset()         { *m = CurrentEraMessage{} }
func (m *CurrentEraMessage) String() string { return proto.CompactTextString(m) }
func (*CurrentEraMessage) ProtoMessage()    {}
func (*CurrentEraMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9bd04e96b3f1608, []int{0}
}

func (m *CurrentEraMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CurrentEraMessage.Unmarshal(m, b)
}
func (m *CurrentEraMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CurrentEraMessage.Marshal(b, m, deterministic)
}
func (m *CurrentEraMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrentEraMessage.Merge(m, src)
}
func (m *CurrentEraMessage) XXX_Size() int {
	return xxx_messageInfo_CurrentEraMessage.Size(m)
}
func (m *CurrentEraMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrentEraMessage.DiscardUnknown(m)
}

var xxx_messageInfo_CurrentEraMessage proto.InternalMessageInfo

type CurrentEraResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CurrentEraResponse) Reset()         { *m = CurrentEraResponse{} }
func (m *CurrentEraResponse) String() string { return proto.CompactTextString(m) }
func (*CurrentEraResponse) ProtoMessage()    {}
func (*CurrentEraResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9bd04e96b3f1608, []int{1}
}

func (m *CurrentEraResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CurrentEraResponse.Unmarshal(m, b)
}
func (m *CurrentEraResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CurrentEraResponse.Marshal(b, m, deterministic)
}
func (m *CurrentEraResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrentEraResponse.Merge(m, src)
}
func (m *CurrentEraResponse) XXX_Size() int {
	return xxx_messageInfo_CurrentEraResponse.Size(m)
}
func (m *CurrentEraResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrentEraResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CurrentEraResponse proto.InternalMessageInfo

func (m *CurrentEraResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*CurrentEraMessage)(nil), "CurrentEraMessage")
	proto.RegisterType((*CurrentEraResponse)(nil), "CurrentEraResponse")
}

func init() { proto.RegisterFile("proto/era.proto", fileDescriptor_a9bd04e96b3f1608) }

var fileDescriptor_a9bd04e96b3f1608 = []byte{
	// 123 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x2d, 0x4a, 0xd4, 0x03, 0xb3, 0x94, 0x84, 0xb9, 0x04, 0x9d, 0x4b, 0x8b, 0x8a,
	0x52, 0xf3, 0x4a, 0x5c, 0x8b, 0x12, 0x7d, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x53, 0x95, 0x34, 0xb8,
	0x84, 0x10, 0x82, 0x41, 0xa9, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0x42, 0x5c, 0x2c, 0x79,
	0x89, 0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x91, 0x23, 0x17, 0xb3,
	0x6b, 0x51, 0xa2, 0x90, 0x15, 0x17, 0xaf, 0x7b, 0x6a, 0x09, 0x42, 0x8f, 0x90, 0x90, 0x1e, 0x86,
	0xa9, 0x52, 0xc2, 0x7a, 0x98, 0x86, 0x2a, 0x31, 0x24, 0xb1, 0x81, 0x1d, 0x62, 0x0c, 0x08, 0x00,
	0x00, 0xff, 0xff, 0x2d, 0xf9, 0xc8, 0x20, 0x9b, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EraClient is the client API for Era service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EraClient interface {
	GetCurrentEra(ctx context.Context, in *CurrentEraMessage, opts ...grpc.CallOption) (*CurrentEraResponse, error)
}

type eraClient struct {
	cc *grpc.ClientConn
}

func NewEraClient(cc *grpc.ClientConn) EraClient {
	return &eraClient{cc}
}

func (c *eraClient) GetCurrentEra(ctx context.Context, in *CurrentEraMessage, opts ...grpc.CallOption) (*CurrentEraResponse, error) {
	out := new(CurrentEraResponse)
	err := c.cc.Invoke(ctx, "/Era/GetCurrentEra", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EraServer is the server API for Era service.
type EraServer interface {
	GetCurrentEra(context.Context, *CurrentEraMessage) (*CurrentEraResponse, error)
}

func RegisterEraServer(s *grpc.Server, srv EraServer) {
	s.RegisterService(&_Era_serviceDesc, srv)
}

func _Era_GetCurrentEra_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CurrentEraMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EraServer).GetCurrentEra(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Era/GetCurrentEra",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EraServer).GetCurrentEra(ctx, req.(*CurrentEraMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Era_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Era",
	HandlerType: (*EraServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCurrentEra",
			Handler:    _Era_GetCurrentEra_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/era.proto",
}
